require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CiudadesController do

  # This should return the minimal set of attributes required to create a valid
  # Ciudade. As you add validations to Ciudade, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nombre" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CiudadesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ciudades as @ciudades" do
      ciudade = Ciudade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ciudades).should eq([ciudade])
    end
  end

  describe "GET show" do
    it "assigns the requested ciudade as @ciudade" do
      ciudade = Ciudade.create! valid_attributes
      get :show, {:id => ciudade.to_param}, valid_session
      assigns(:ciudade).should eq(ciudade)
    end
  end

  describe "GET new" do
    it "assigns a new ciudade as @ciudade" do
      get :new, {}, valid_session
      assigns(:ciudade).should be_a_new(Ciudade)
    end
  end

  describe "GET edit" do
    it "assigns the requested ciudade as @ciudade" do
      ciudade = Ciudade.create! valid_attributes
      get :edit, {:id => ciudade.to_param}, valid_session
      assigns(:ciudade).should eq(ciudade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ciudade" do
        expect {
          post :create, {:ciudade => valid_attributes}, valid_session
        }.to change(Ciudade, :count).by(1)
      end

      it "assigns a newly created ciudade as @ciudade" do
        post :create, {:ciudade => valid_attributes}, valid_session
        assigns(:ciudade).should be_a(Ciudade)
        assigns(:ciudade).should be_persisted
      end

      it "redirects to the created ciudade" do
        post :create, {:ciudade => valid_attributes}, valid_session
        response.should redirect_to(Ciudade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ciudade as @ciudade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudade.any_instance.stub(:save).and_return(false)
        post :create, {:ciudade => { "nombre" => "invalid value" }}, valid_session
        assigns(:ciudade).should be_a_new(Ciudade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudade.any_instance.stub(:save).and_return(false)
        post :create, {:ciudade => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ciudade" do
        ciudade = Ciudade.create! valid_attributes
        # Assuming there are no other ciudades in the database, this
        # specifies that the Ciudade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ciudade.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => ciudade.to_param, :ciudade => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested ciudade as @ciudade" do
        ciudade = Ciudade.create! valid_attributes
        put :update, {:id => ciudade.to_param, :ciudade => valid_attributes}, valid_session
        assigns(:ciudade).should eq(ciudade)
      end

      it "redirects to the ciudade" do
        ciudade = Ciudade.create! valid_attributes
        put :update, {:id => ciudade.to_param, :ciudade => valid_attributes}, valid_session
        response.should redirect_to(ciudade)
      end
    end

    describe "with invalid params" do
      it "assigns the ciudade as @ciudade" do
        ciudade = Ciudade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudade.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciudade.to_param, :ciudade => { "nombre" => "invalid value" }}, valid_session
        assigns(:ciudade).should eq(ciudade)
      end

      it "re-renders the 'edit' template" do
        ciudade = Ciudade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudade.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciudade.to_param, :ciudade => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ciudade" do
      ciudade = Ciudade.create! valid_attributes
      expect {
        delete :destroy, {:id => ciudade.to_param}, valid_session
      }.to change(Ciudade, :count).by(-1)
    end

    it "redirects to the ciudades list" do
      ciudade = Ciudade.create! valid_attributes
      delete :destroy, {:id => ciudade.to_param}, valid_session
      response.should redirect_to(ciudades_url)
    end
  end

end
