require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfrecesController do

  # This should return the minimal set of attributes required to create a valid
  # Ofrece. As you add validations to Ofrece, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "id_restaurante" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfrecesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ofreces as @ofreces" do
      ofrece = Ofrece.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ofreces).should eq([ofrece])
    end
  end

  describe "GET show" do
    it "assigns the requested ofrece as @ofrece" do
      ofrece = Ofrece.create! valid_attributes
      get :show, {:id => ofrece.to_param}, valid_session
      assigns(:ofrece).should eq(ofrece)
    end
  end

  describe "GET new" do
    it "assigns a new ofrece as @ofrece" do
      get :new, {}, valid_session
      assigns(:ofrece).should be_a_new(Ofrece)
    end
  end

  describe "GET edit" do
    it "assigns the requested ofrece as @ofrece" do
      ofrece = Ofrece.create! valid_attributes
      get :edit, {:id => ofrece.to_param}, valid_session
      assigns(:ofrece).should eq(ofrece)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ofrece" do
        expect {
          post :create, {:ofrece => valid_attributes}, valid_session
        }.to change(Ofrece, :count).by(1)
      end

      it "assigns a newly created ofrece as @ofrece" do
        post :create, {:ofrece => valid_attributes}, valid_session
        assigns(:ofrece).should be_a(Ofrece)
        assigns(:ofrece).should be_persisted
      end

      it "redirects to the created ofrece" do
        post :create, {:ofrece => valid_attributes}, valid_session
        response.should redirect_to(Ofrece.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ofrece as @ofrece" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ofrece.any_instance.stub(:save).and_return(false)
        post :create, {:ofrece => { "id_restaurante" => "invalid value" }}, valid_session
        assigns(:ofrece).should be_a_new(Ofrece)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ofrece.any_instance.stub(:save).and_return(false)
        post :create, {:ofrece => { "id_restaurante" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ofrece" do
        ofrece = Ofrece.create! valid_attributes
        # Assuming there are no other ofreces in the database, this
        # specifies that the Ofrece created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ofrece.any_instance.should_receive(:update_attributes).with({ "id_restaurante" => "1" })
        put :update, {:id => ofrece.to_param, :ofrece => { "id_restaurante" => "1" }}, valid_session
      end

      it "assigns the requested ofrece as @ofrece" do
        ofrece = Ofrece.create! valid_attributes
        put :update, {:id => ofrece.to_param, :ofrece => valid_attributes}, valid_session
        assigns(:ofrece).should eq(ofrece)
      end

      it "redirects to the ofrece" do
        ofrece = Ofrece.create! valid_attributes
        put :update, {:id => ofrece.to_param, :ofrece => valid_attributes}, valid_session
        response.should redirect_to(ofrece)
      end
    end

    describe "with invalid params" do
      it "assigns the ofrece as @ofrece" do
        ofrece = Ofrece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ofrece.any_instance.stub(:save).and_return(false)
        put :update, {:id => ofrece.to_param, :ofrece => { "id_restaurante" => "invalid value" }}, valid_session
        assigns(:ofrece).should eq(ofrece)
      end

      it "re-renders the 'edit' template" do
        ofrece = Ofrece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ofrece.any_instance.stub(:save).and_return(false)
        put :update, {:id => ofrece.to_param, :ofrece => { "id_restaurante" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ofrece" do
      ofrece = Ofrece.create! valid_attributes
      expect {
        delete :destroy, {:id => ofrece.to_param}, valid_session
      }.to change(Ofrece, :count).by(-1)
    end

    it "redirects to the ofreces list" do
      ofrece = Ofrece.create! valid_attributes
      delete :destroy, {:id => ofrece.to_param}, valid_session
      response.should redirect_to(ofreces_url)
    end
  end

end
